default_kwargs: &default_kwargs
  data_dir: /home/data/
  desc_file: /home/instructions.txt
  agent.steps: 50
  agent.search.max_debug_depth: 20
  copy_data: True
  agent.search.debug_prob: 1
  agent.expose_prediction: True
  agent.time_limit: 10800
  exec.timeout: 3600
  exp_name: bench

kwargs_type: omegaconf
start: aide/start.sh
kwargs:
  <<: *default_kwargs
  agent.code.model: openai/gpt-oss-120b:exacto
  agent.feedback.model: openai/gpt-oss-120b:exacto
  report.model: openai/gpt-oss-120b:exacto
env_vars:
  TIME_LIMIT_SECS: 10800 #time in seconds
  http_proxy: http://4VycCrzHCd:pIU9pvdGwW@37.252.6.53:32900
  https_proxy: http://4VycCrzHCd:pIU9pvdGwW@37.252.6.53:32900
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} #export OPENAI_API_KEY on host
  # OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }} #export OPENAI_BASE_URL on host for custom openai compatible api
  # VERTEX=true #use vertex models
  # VERTEX_SERVICE_ACCOUNT=${AGENT_DIR}/service_account.json #path to service account credentials for vertex on host
