default_kwargs: &default_kwargs
  data-dir: /home/data/
  provider: openai
  description: /home/agent/full_instructions.txt
  exp-name: bench
  max-steps: 100
  time-limit: 10800
  tool-timeout: 3600

kwargs_type: argparse
start: react/start.sh
kwargs:
  <<: *default_kwargs
  model: openai/gpt-oss-120b
env_vars:
  TIME_LIMIT_SECS: 10800 
  # http_proxy: *
  # https_proxy: *
  API_KEY: ${{ secrets.API_KEY }}
  BASE_URL: ${{ secrets.BASE_URL }}
  # VERTEX=true #use vertex models
  # VERTEX_SERVICE_ACCOUNT=${AGENT_DIR}/service_account.json #path to service account credentials for vertex on host
