default_kwargs: &default_kwargs
  data-dir: /home/data/
  provider: openai
  description: /home/instructions.txt
  exp-name: bench
  max-steps: 100

kwargs_type: argparse
start: react/start.sh
kwargs:
  <<: *default_kwargs
  model: gpt-4.1-mini
env_vars:
  TIME_LIMIT_SECS: 10800 #time in seconds
  http_proxy: http://4VycCrzHCd:pIU9pvdGwW@37.252.6.53:32900
  https_proxy: http://4VycCrzHCd:pIU9pvdGwW@37.252.6.53:32900
  API_KEY: ${{ secrets.API_KEY }}
  #BASE_URL: ${{ secrets.BASE_URL }}
  # VERTEX=true #use vertex models
  # VERTEX_SERVICE_ACCOUNT=${AGENT_DIR}/service_account.json #path to service account credentials for vertex on host
